### ISSUE TITLE
City options are None

### ISSUE THREAD

**Issue by MDAmirPathan** [HackForChangeIN/HFC#212]
### check form data **Signup as a member**

may be cause line is **commented**
https://github.com/HackForChangeIN/HFC/blob/ddb93b8ffde4f704b2359046f87a44bcf3cded65/HFCCore/forms.py#L119

or
issue in retrieving data from server
https://github.com/HackForChangeIN/HFC/blob/ddb93b8ffde4f704b2359046f87a44bcf3cded65/HFCCore/models.py#L106

![Screenshot (1)](https://user-images.githubusercontent.com/75565798/134669387-67882aa9-2412-4591-bfe4-e0b3be5d7152.png)

**Comment by Sambit009** [comment]
Community member Signup form city value issue resolved

**Comment by Sambit009** [comment]
Thank you Amir for pointing this issue, that issue is solved now.
